### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kuljeet-123**
Fixes issue:#9.

Changes:
Updated the README of the project.

### CODE REVIEW

**Comment by xlogix** [comment]
Need a lot of changes here @Kuljeet-123. The description doesn't explain the role of this app & you haven't described the steps to run the app as well. Don't just copy/paster things from the main repo. Put some efforts here.

**Comment by xlogix** [comment]
And you raised a PR on your own repo 🤣

**Comment by Kuljeet-123** [comment]
@xlogix sorry for that.Let me make the changes.

**Comment by Kuljeet-123** [comment]
@xlogix Can you please tell me where I would find the description of the app.Any link or documentation.

**Pull request merged**
